# Generated by Django 4.2.9 on 2024-01-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_course1_course2_course3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_selection', models.CharField(choices=[('course1', 'COURSE1'), ('course2', 'COURSE2'), ('course2', 'COURSE2')], default='user', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('booking_date', models.DateField()),
                ('booking_time', models.CharField(max_length=5)),
                ('number_of_attendees', models.IntegerField(default=2)),
                ('booking_status', models.IntegerField(choices=[(0, 'Awaiting Confirmation'), (1, 'Confirm Booking'), (2, 'Booking Declined')], default=0)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.account')),
            ],
        ),
    ]
