# Generated by Django 4.2.9 on 2024-01-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='SOME STRING', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='SOME STRING', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='SOME STRING', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='SOME STRING', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='course_selection',
            field=models.CharField(choices=[('course1', 'COURSE1 - Boys Aged 7-14 (60euros per boy)'), ('course2', 'COURSE2 - Boys Aged 14-21 (80euros per boy)'), ('course2', 'COURSE2 - Girls Aged 9-14 (40euros per girl)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_attendees',
            field=models.IntegerField(default=1),
        ),
    ]
