# Generated by Django 4.2.9 on 2024-01-26 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0004_remove_account_name_account_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='account',
        ),
    ]
