# Generated by Django 4.2.9 on 2024-01-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0007_booknow_delete_account_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='SOME STRING', max_length=200, unique=True)),
                ('last_name', models.CharField(default='SOME STRING', max_length=200, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('photo', models.ImageField(unique=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('course_selection', models.CharField(choices=[('course1', 'COURSE1 - Boys Aged 7-14 (60euros per boy)'), ('course2', 'COURSE2 - Boys Aged 14-21 (80euros per boy)'), ('course2', 'COURSE2 - Girls Aged 9-14 (40euros per girl)')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('booking_date', models.DateField()),
                ('booking_time', models.CharField(max_length=5)),
                ('number_of_attendees', models.IntegerField(default=1)),
                ('booking_status', models.IntegerField(choices=[(0, 'Awaiting Confirmation'), (1, 'Confirm Booking'), (2, 'Booking Declined')], default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='BookNow',
        ),
    ]
