# Generated by Django 4.2.9 on 2024-02-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='venue_selection',
            field=models.CharField(choices=[('venue1', 'VENUE1 - Portloaise'), ('venue2', 'VENUE2 - Tullamore)'), ('venue3', 'VENUE3 - Mullingar')], default='SOME STRING', max_length=100),
            preserve_default=False,
        ),
    ]
