# Generated by Django 4.2.9 on 2024-01-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='venue_selection',
            field=models.CharField(choices=[('venue1', 'Portloaise'), ('venue2', 'Tullamore'), ('venue3', 'Mullingar')], default='SOME STRING', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='course_selection',
            field=models.CharField(choices=[('course1', 'COURSE1 - Boys Aged 7-14 (60euros per boy)'), ('course2', 'COURSE2 - Boys Aged 14-21 (80euros per boy)'), ('course3', 'COURSE3 - Girls Aged 9-14 (40euros per girl)')], max_length=10),
        ),
    ]
