# Generated by Django 4.2.9 on 2024-01-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_booking_venue_selection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='venue_selection',
            field=models.CharField(choices=[('venue1', 'Portloaise'), ('venue2', 'Tullamore'), ('venue3', 'Mullingar')], max_length=20),
        ),
    ]
