# Generated by Django 4.2.9 on 2024-02-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_booking_venue_selection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='course_selection',
            field=models.CharField(choices=[('Boys Aged 7-14 (60euros per boy)', 'COURSE1 - Boys Aged 7-14 (60euros per boy)'), ('Boys Aged 14-21 (80euros per boy)', 'COURSE2 - Boys Aged 14-21 (80euros per boy)'), ('Girls Aged 9-14 (40euros per girl)', 'COURSE3 - Girls Aged 9-14 (40euros per girl)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='venue_selection',
            field=models.CharField(choices=[('Portloaise', 'VENUE1 - Portloaise'), ('Tullamore', 'VENUE2 - Tullamore'), ('Mullingar', 'VENUE3 - Mullingar')], max_length=100),
        ),
    ]
