# Generated by Django 4.2.9 on 2024-01-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0004_remove_booking_venue_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='course_selection',
            field=models.CharField(choices=[('course1', 'COURSE1 - Boys Aged 7-14 (60euros per boy)'), ('course2', 'COURSE2 - Boys Aged 14-21 (80euros per boy)'), ('course3', 'COURSE3 - Girls Aged 9-14 (40euros per girl)')]),
        ),
    ]
